In [20]:
import joblib
import numpy as np
import pandas as pd

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)

X_train_processed = joblib.load("../models/classification/X_train_processed.pkl")
X_test_processed = joblib.load("../models/classification/X_test_processed.pkl")
y_train = joblib.load("../models/classification/y_train.pkl")
y_test = joblib.load("../models/classification/y_test.pkl")


# Logistic Regression
logistic = LogisticRegression()
logistic.fit(X_train_processed, y_train)
logistic_pred = logistic.predict(X_test_processed)

logistic_accuracy = accuracy_score(y_test, logistic_pred)
logistic_precision = precision_score(y_test, logistic_pred, average='weighted')
logistic_recall = recall_score(y_test, logistic_pred, average='weighted')
logistic_f1 = f1_score(y_test, logistic_pred, average='weighted')
confusion = confusion_matrix(y_test, logistic_pred)

print("Logistic Regression :")
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1 Score: {f1}")
print(f"Confusion Matrix:\n{confusion}")

print()

# Decision Tree
tree = DecisionTreeClassifier(random_state=42)
tree.fit(X_train_processed, y_train)
tree_pred = tree.predict(X_test_processed)

tree_accuracy = accuracy_score(y_test, tree_pred)
tree_precision = precision_score(y_test, tree_pred, average='weighted')
tree_recall = recall_score(y_test, tree_pred, average='weighted')
tree_f1 = f1_score(y_test, tree_pred, average='weighted')
confusion = confusion_matrix(y_test, tree_pred)

print("DecisionTreeClassifier:")
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1 Score: {f1}")
print(f"Confusion Matrix:\n{confusion}")

print()

# Random Forest
forest = RandomForestClassifier(random_state=42)
forest.fit(X_train_processed, y_train)
forest_pred = forest.predict(X_test_processed)

forest_accuracy = accuracy_score(y_test, forest_pred)
forest_precision = precision_score(y_test, forest_pred, average='weighted')
forest_recall = recall_score(y_test, forest_pred, average='weighted')
forest_f1 = f1_score(y_test, forest_pred, average='weighted')
confusion = confusion_matrix(y_test, forest_pred)

print("RandomForestClassifier:")
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1 Score: {f1}")
print(f"Confusion Matrix:\n{confusion}")

print()

results = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Decision Tree",
        "Random Forest"
    ],
    "Accuracy": [
        logistic_accuracy,
        tree_accuracy,
        forest_accuracy
    ],
    "Precision": [
        logistic_precision,
        tree_precision,
        forest_precision
    ],
    "Recall": [
        logistic_recall,
        tree_recall,
        forest_recall
    ],
    "F1": [
        logistic_f1,
        tree_f1,
        forest_f1
    ]
})

print(results)


joblib.dump(logistic,"../models/classification/best_classification_model.pkl")


results.to_csv("../models/classification/classification_results.csv",index=False)




c:\Users\adida\OneDrive\Desktop\AB PROJECTS\PriceView\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Logistic Regression :
Accuracy: 0.8323061952643529
Precision: 0.8322039575462903
Recall: 0.8323061952643529
F1 Score: 0.8322447863113062
Confusion Matrix:
[[896 122   2]
 [113 844  86]
 [  2 108 910]]

DecisionTreeClassifier:
Accuracy: 0.8323061952643529
Precision: 0.8322039575462903
Recall: 0.8323061952643529
F1 Score: 0.8322447863113062
Confusion Matrix:
[[877 137   6]
 [159 770 114]
 [  7 138 875]]

RandomForestClassifier:
Accuracy: 0.8323061952643529
Precision: 0.8322039575462903
Recall: 0.8323061952643529
F1 Score: 0.8322447863113062
Confusion Matrix:
[[888 128   4]
 [141 785 117]
 [  1 126 893]]

                 Model  Accuracy  Precision    Recall        F1
0  Logistic Regression  0.859552   0.860744  0.859552  0.860049
1        Decision Tree  0.818034   0.818414  0.818034  0.818145
2        Random Forest  0.832306   0.832204  0.832306  0.832245
